name: Continuous Integration and QA

on:
  push:
    paths-ignore:
      # don't need to build and test changes to documentation
      - "*.md"
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build-and-test:

    name: build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        # test with the last 2 Node.js LTS versions
        node-version: [22.x, 24.x]

    steps:

      - name: Checkout changes
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always
        #   fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
        #   retry-on-snapshot-warnings: true

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        # lockfile should have been updated locally prior pushing changes to the repository!
        run: pnpm --silent install --frozen-lockfile

      - name: Lint
        # Linting using "@antfu/eslint-config"
        run: pnpm --silent lint

      - name: Test
        # Testing using ts-jest hence no need to build forehand
        run: pnpm --silent test

      - name: Build
        # Final build to "./dist" folder
        run: pnpm --silent build
